# Generated by Django 3.2.4 on 2021-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, default=' ', max_length=60, null=True)),
                ('codigo', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
