# Generated by Django 3.2.4 on 2021-09-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_delete_docente_disciplina'),
        ('configuracao', '0003_disciplina_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
