# Generated by Django 3.2.4 on 2021-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0004_delete_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado_Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, default=' ', max_length=60, null=True)),
            ],
        ),
    ]
