# Generated by Django 3.2.4 on 2021-10-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_resultado_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_identificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(blank=True, default=' ', max_length=3, null=True)),
                ('descricao', models.CharField(blank=True, default=' ', max_length=60, null=True)),
            ],
        ),
    ]
