# Generated by Django 3.2.4 on 2021-09-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('graduacao', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('funcao', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
