# Generated by Django 3.2.4 on 2021-10-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.docente')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='disciplina.disciplina')),
                ('estado', models.CharField(blank=True, default='Ativado', max_length=19, null=True)),
                ('data_registro', models.CharField(max_length=20)),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
