# Generated by Django 3.2.4 on 2021-09-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_docente_disciplina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente_Disciplina',
        ),
    ]
