# Generated by Django 3.2.4 on 2021-09-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nome_mae', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.genero')),
                ('data_nascimento', models.CharField(max_length=20)),
                ('bi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('passaporte', models.CharField(blank=True, default=' ', max_length=55, null=True)),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.estado_civil')),
                ('residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=190, null=True)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='configuracao.provincia')),
                ('municipio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='configuracao.municipio')),
                ('nacionalidade', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.pais')),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
