# Generated by Django 3.2.4 on 2021-09-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(default=1, upload_to='uploads/fotos/% Y/'),
            preserve_default=False,
        ),
    ]
