# Generated by Django 3.2.4 on 2021-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='bi',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='passaporte',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ndi',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
