# Generated by Django 3.2.4 on 2021-10-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0006_documento_identificacao'),
        ('pessoa', '0004_auto_20211011_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.documento_identificacao'),
            preserve_default=False,
        ),
    ]
