# Generated by Django 3.2.4 on 2021-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_pessoa_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(blank=True, default='foto/user.jpg', null=True, upload_to='uploads/fotos/% Y/'),
        ),
    ]
