# Generated by Django 3.2.4 on 2021-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_alter_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(blank=True, default='user.jpg', null=True, upload_to='uploads/fotos/% Y/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ndi',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
