# Generated by Django 3.2.4 on 2021-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20211016_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(blank=True, default='user.jpg', null=True, upload_to='foto/%Y/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ndi',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
