# Generated by Django 3.2.4 on 2021-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_alter_pessoa_ndi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(blank=True, default='user.jpg', null=True, upload_to='foto/%Y'),
        ),
    ]
