# Generated by Django 3.2.4 on 2021-09-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('nota_final', models.CharField(blank=True, max_length=3, null=True)),
                ('instituicao_origem', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('data_registro', models.CharField(max_length=20)),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
