# Generated by Django 3.2.4 on 2021-09-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.periodo')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='configuracao.resultado_inscricao')),
                ('nota_final', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('instituicao_origem', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('data_registro', models.CharField(max_length=20)),
                ('data_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
