# Generated by Django 3.2.4 on 2021-09-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_inscricao_operador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='data_registro',
            new_name='data_inscricao',
        ),
    ]
