# Generated by Django 3.2.4 on 2021-10-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_resultado_inscricao'),
        ('aluno', '0004_rename_data_registro_inscricao_data_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nota_final',
            new_name='media_conclusao',
        ),
        migrations.RenameField(
            model_name='inscricao',
            old_name='nota_final',
            new_name='ano_conclusao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='resultado',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='habilitacao_literaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='configuracao.grau_academico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='media_conclusao',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='configuracao.curso'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='aluno',
            order_with_respect_to='pessoa',
        ),
    ]
