# Generated by Django 3.2.4 on 2021-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_auto_20211011_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='numero_inscricao',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
