# Generated by Django 3.2.4 on 2021-10-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_inscricao_numero_inscricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
