# Generated by Django 3.2.4 on 2021-10-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.inscricao')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='configuracao.resultado_inscricao')),
                ('descricao', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('data', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('operador', models.CharField(blank=True, max_length=190, null=True)),
            ],
        ),
    ]
